CODES_DICT = {
    176: "There was problem with .env file on the server.",
    143: "Both skip_verify and skip_db_search set to True.",
    153: "At least one of the images doesn't exist. Consult log.",
    111: "Length of img_paths is zero.",
    630: "Could not detect a face in any of the images.",
    126: "Regex matched ID.",
    127: "Regex didn't match ID.",
    119: "Files uploaded successfully.",
    120: "All the files were rejected due to not meeting score criteria.",
    117: "Length of uploaded files was zero.",
    155: "Database connection error. Consult log.",
    100: "None of the matching IDs in the DB matched what was given.",
    134: "After a search in the DB, the ID matched with what was found.",
    116: "Problem getting ID, please check MySQL settings.",
    113: "Path in the MySQL database doesn't exist in the image database.",
    200: "Image successfully verified.",
    500: "Image failed to verify and DB search was not enabled or was not a success.",
    150: "Insert into MySQL failed. Please check your settings.",
    152: "Failed to detect face in any of the images or all contained more than one face.",
    178: "Problem loading liveness detection model. Check your URL.",
    560: "All faces were spoof.",
    143: "Both skip_verify and skip_db_search set to True. One must be False.",
    900: "ID already exists in db and in_place was set to true. Folder deleted and DB path replaced.",
    838: "ID successfully inserted into DB. in_place was needlessly enabled.",
    800: "ID successfully inserted to db.",
    850: "ID successfully inserted to db. in_place was disabled, so the files were added to the previous ones.",
    189: "Folder already uploaded to DB. Can't verify to upload again.",
    107: "Endpoint request needs to be www-form-urlencoded, or form is empty.",
    108: "Acceptable upload_db endpoint www-form-urlencoded keys: upload_id, name, delete_pickles, rebuild_db, in_place.",
    109: "Acceptable verify endpoint www-form-urlencoded keys: upload_id, skip_verify, skip_db_search, skip_liveness",
    110: "No args provided for upload_imgs endpoint, or id arg must be provided through upload_imgs?id="

}