name: reco3
channels:
  - default
dependencies:
  - python=3.9
  - flask
  - pip:
    - git+https://github.com/ipazc/mtcnn.git
    - deepface
    - mysql-connector-python
    - opencv-python
    - imgaug
    - flask
    - python-dotenv
    - gdown
    - imagecorruptions
    - image-quality
    - joblib
    - tqdm
    - flask-cors
    - tensorflow
    - gunicorn
