name: reco3
channels:
  - defaults
dependencies:
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrs==21.2.0
    - bidict==0.21.2
    - binaryornot==0.4.4
    - cachetools==4.2.2
    - chardet==4.0.0
    - click==8.0.1
    - colorama==0.4.4
    - cycler==0.10.0
    - decorator==4.4.2
    - deepface==0.0.63
    - dnspython==2.1.0
    - filelock==3.0.12
    - flask==2.0.1
    - flask-cors==3.0.10
    - flatbuffers==1.12
    - from-root==1.0.1
    - gast==0.4.0
    - gdown==3.13.0
    - google-auth==1.32.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - gunicorn==20.1.0
    - h5py==3.1.0
    - idna==2.10
    - image-quality==1.2.7
    - imagecorruptions==1.1.2
    - imageio==2.9.0
    - imgaug==0.4.0
    - imutils==0.5.4
    - itsdangerous==2.0.1
    - jinja2==3.0.1
    - joblib==1.0.1
    - keras==2.4.3
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - libsvm==3.23.0.4
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - mtcnn==0.1.0
    - multidict==5.1.0
    - mysql-connector-python==8.0.25
    - networkx==2.5.1
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opencv-python==4.5.2.54
    - opt-einsum==3.3.0
    - pandas==1.2.5
    - pillow==8.3.0
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymongo==3.11.4
    - pyparsing==2.4.7
    - pysocks==1.7.1
    - python-dateutil==2.8.1
    - python-dotenv==0.18.0
    - python-engineio==4.2.1
    - python-socketio==5.4.0
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - retina-face==0.0.4
    - rsa==4.7.2
    - scikit-image==0.18.2
    - scipy==1.7.0
    - shapely==1.7.1
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - termcolor==1.1.0
    - tifffile==2021.7.2
    - tqdm==4.61.1
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - websockets==9.1
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - yarl==1.6.3
